base_model: Qwen/Qwen2-7B-Instruct

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: lightblue/qarasu_m_train
    type: sharegpt
    conversation: qwen-7b-chat
dataset_prepared_path: /workspace/prepared_qwen2_7B_instruct_qarasu_m
val_set_size: 0.01
output_dir: /workspace/output_qwen2_7B_instruct_qarasu_m

eval_sample_packing: True

sequence_len: 32000
sample_packing: true
pad_to_sequence_len: true
train_on_inputs: false

use_wandb: true
wandb_project: axolotl
wandb_entity: peterd
wandb_name: qwen2_7B_instruct_qarasu_m

gradient_accumulation_steps: 1
micro_batch_size: 1
num_epochs: 1
optimizer: paged_adamw_8bit
lr_scheduler: cosine
learning_rate: 2e-5

group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 100
evals_per_epoch: 10
eval_table_size:
saves_per_epoch: 1
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  pad_token: <|end_of_text|>
